version: '3.8'

services:
  db:
    image: postgres:16
    container_name: payslip_db
    restart: always
    environment:
      POSTGRES_USER: payslip_user
      POSTGRES_PASSWORD: payslip_pass
      POSTGRES_DB: payslip_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: payslip_app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres_data:
